version: '3'

networks:
  contato:
  nginx:
  mysql:
  artisan:
  composer:
  phpunit:

services:
  nginx:
    image: nginx:stable-alpine
    container_name: app_contato_nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./:/var/www/html
      - ./.nginx/default.conf:/etc/nginx/conf.d/default.conf
      - $CERTS_FOLDER/app-contato/nginx-selfsigned.crt:/etc/ssl/certs/nginx-selfsigned.crt
      - $CERTS_FOLDER/app-contato/nginx-selfsigned.key:/etc/ssl/private/nginx-selfsigned.key
    depends_on:
      - php
      - mysql
    networks:
      - nginx

  mysql:
    image: mysql/mysql-server:8.0.23
    container_name: app_contato_mysql
    restart: unless-stopped
    tty: true
    volumes:
      - ./.mysql:/var/lib/mysql
    environment:
      MYSQL_DATABASE: homestead
      MYSQL_USER: homestead
      MYSQL_PASSWORD: secret
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_ROOT_HOST: "%"
      SERVICE_TAGS: dev
      SERRVICE_NAME: mysql
    command:
            - "--default-authentication-plugin=mysql_native_password"
    networks:
      - mysql

  php:
    user: "${UID}:${GID}"
    build:
      context: .
      dockerfile: Dockerfile
    container_name: app_contato_php
    volumes:
      - ./:/var/www/html
    networks:
      - contato
      - nginx
      - mysql

  composer:
    user: "${UID}:${GID}"
    build:
      context: .
      dockerfile: Dockerfile
    container_name: app_contato_composer
    volumes:
      - ./:/var/www/html

    working_dir: /var/www/html
    entrypoint: ['composer']
    networks:
      - nginx
      - composer
      - mysql

  artisan:
    user: "${UID}:${GID}"
    build:
      context: .
      dockerfile: Dockerfile
    container_name: app_contato_artisan
    volumes:
      - ./:/var/www/html
    depends_on:
      - mysql
    working_dir: /var/www/html
    entrypoint: ['/var/www/html/artisan']
    environment:
      PHP_MEMORY_LIMIT: 512M
    networks:
      - artisan
      - mysql

  phpunit:
    user: "${UID}:${GID}"
    build:
      context: .
      dockerfile: Dockerfile
    container_name: app_contato_phpunit
    volumes:
      - ./:/var/www/html
    depends_on:
      - mysql
    working_dir: /var/www/html
    entrypoint: ['/var/www/html/vendor/bin/phpunit']
    environment:
      PHP_MEMORY_LIMIT: 512M
    networks:
      - mysql
      - phpunit
